channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.7.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - awscli=2.22.19
  - awscrt=0.23.4
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - bokeh=3.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cryptography=43.0.1
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2024.12.1
  - dask-core=2024.12.1
  - dask-expr=1.1.21
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.12.1
  - distro=1.8.0
  - docutils=0.18.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.10.0
  - gflags=2.2.2
  - glog=0.7.1
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.4.1
  - h5py=3.12.1
  - hdf5=1.14.4
  - holoviews=1.20.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hvplot=0.11.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.17.2
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jmespath=1.0.1
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.32.0
  - libgoogle-cloud-storage=2.32.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libparquet=18.1.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.0.2
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - nbclient=0.10.1
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.3.1
  - notebook-shim=0.2.4
  - numpy=2.2.0
  - openjpeg=2.5.3
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - panel=1.5.5
  - param=2.2.0
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pyviz_comms=3.0.3
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - ruamel.yaml=0.17.17
  - ruamel.yaml.clib=0.2.8
  - s2n=1.5.9
  - send2trash=1.8.3
  - setuptools=75.6.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.6.3
  - tblib=3.0.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - uc-micro-py=1.0.3
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=1.26.19
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xarray=2024.11.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.2
  - zstd=1.5.6
